config/routes.rb
Imageaudit::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      post :change_keeppublished
      post :set_notes
      put :set_notes
    end
  end

  resources :communities, :only => [:index, :show]
  resources :audit_logs, :only => [:index, :show]

  resources :images, :only => [:index, :show] do
    member do
      post :change_stock
      post :change_communityreview
      post :change_staffreview
      post :set_notes
      put :set_notes
    end
  end

  match '/bulk_change_stock_and_staff_review', to: 'images#bulk_change_stock_and_staff_review'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

end

app/models/audit_log.rb
# === COPYRIGHT:
# Copyright (c) North Carolina State University
# Developed with funding from the eXtension Foundation
# === LICENSE:
#
# see LICENSE file

class AuditLog < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  default_url_options[:host] = Settings.urlwriter_host

  belongs_to :auditable, :polymorphic => true
  belongs_to :contributor
  after_create :queue_slack_notification

  NOTES_SOURCES = ['notes','copyright','source']

  def audit_type
    if(self.auditable_type == "HostedImage")
      'Image'
    elsif(self.auditable_type == "Page")
      'Page'
    else
      self.auditable_type
    end
  end

  def auditable_type_string
    case self.audit_type
    when 'Image'
      'an image'
    when 'Page'
      'a page'
    else
      "a #{self.audit_type.downcase}"
    end
  end

  def notification_url
    audit_log_url(self)
  end

  def auditable_url
    ao = self.changed_object
    if(ao.class.name == 'HostedImage')
      image_url(ao.id)
    elsif(ao.class.name == 'Page')
      page_url(ao.id)
    else
      "#{audit_log.audit_type} ID# #{ao.id}"
    end
  end

  def changed_object
    self.auditable
  end


  def queue_slack_notification
    if(Settings.sidekiq_enabled)
      self.class.delay.delayed_slack_notification(self.id)
    else
      self.slack_notification
    end
  end

  def self.delayed_slack_notification(record_id)
    if(record = find_by_id(record_id))
      record.slack_notification
    end
  end

  def audit_action_string
    return_string_array = []
    if(NOTES_SOURCES.include?(self.changed_item))
      if(self.changed_item == 'copyright')
        return_string_array << "The copyright value for #{auditable_type_string} was changed."
      elsif(self.changed_item == 'notes')
        return_string_array << "#{self.contributor.fullname} audited #{auditable_type_string} changing the notes."
      elsif(self.changed_item == 'source')
        return_string_array << "The source for #{auditable_type_string} was changed to `#{self.current_notes}` from `#{self.previous_notes}`"
      else
        return_string_array << "#{self.contributor.fullname} audited #{auditable_type_string}"
      end
    elsif(self.changed_item == 'link')
      return_string_array << "#{auditable_type_string.capitalize} was linked to a published page."
    else
      return_string_array << "#{self.contributor.fullname} audited #{auditable_type_string}"
      if(current_check_value.nil?)
        return_string_array << "clearing the value for `#{self.changed_item}`"
      elsif(previous_check_value.nil?)
        return_string_array << "setting the value of `#{self.changed_item}`"
        return_string_array << "to #{(self.current_check_value? ? '`True`' : '`False`')}"
      else
        return_string_array << "changing the value of #{self.changed_item}"
        return_string_array << "from #{(self.previous_check_value? ? '`True`' : '`False`')}"
        return_string_array << "to #{(self.current_check_value? ? '`True`' : '`False`')}"
      end
    end
    return_string_array.join(' ')
  end


  def slack_notification
    return false if self.changed_item == 'source'
    ao = self.changed_object
    post_options = {}
    post_options[:channel] = Settings.imageaudit_slack_channel
    post_options[:username] = "ImageAudit Log Notification"

    attachment = { "fallback" => "#{self.contributor.fullname} audited #{auditable_type_string}  Details [TBD].",
    "mrkdwn_in" => ["fields"],
    "text" => "ImageAudit Log Notification",
    "fields" => [
      {
        "title" => "Who",
        "value" => "#{self.contributor.fullname}",
        "short" => true
      },
      {
        "title" => "What",
        "value" =>  "#{self.audit_type.capitalize} #{ao.nil? ? "ID# Unknown (removed #{self.audit_type.downcase})" : "ID# #{ao.id}" }",
        "short" =>  true
      }
    ],
    "color" => "good"
    }

    if(self.changed_item == 'notes')
      attachment["fields"].push({"title" => "Action", "value" => self.audit_action_string, "short" => false})
      attachment["fields"].push({"title" => "Previous Notes", "value" => (self.previous_notes.blank? ? 'n/a' : self.previous_notes.html_safe), "short" => false})
      attachment["fields"].push({"title" => "Current Notes", "value" => (self.current_notes.blank? ? 'n/a' : self.current_notes.html_safe), "short" => false})
    elsif(self.changed_item == 'copyright')
      attachment["fields"].push({"title" => "Action", "value" => self.audit_action_string, "short" => false})
      attachment["fields"].push({"title" => "Previous Copyright", "value" => (self.previous_notes.blank? ? 'n/a' : self.previous_notes.html_safe), "short" => false})
      attachment["fields"].push({"title" => "Current Copyright", "value" => (self.current_notes.blank? ? 'n/a' : self.current_notes.html_safe), "short" => false})
    elsif(self.changed_item == 'link')
      attachment["fields"].push({"title" => "Action", "value" => ":new: #{self.audit_action_string}", "short" => false})
      attachment["fields"].push({"title" => "ImageAudit Image", "value" => self.auditable_url, "short" => false})
      attachment["fields"].push({"title" => "Image Description", "value" => (ao.description.blank? ? 'n/a' : ao.description.html_safe), "short" => false})
      attachment["fields"].push({"title" => "Copyright", "value" => (ao.copyright.blank? ? 'n/a' : ao.copyright.html_safe), "short" => false})
    else
      attachment["fields"].push({"title" => "Action", "value" => self.audit_action_string, "short" => false})
    end
    attachment["fields"].push({"title" => "Details", "value" => self.notification_url, "short" => false})
    post_options[:attachment] = attachment
    SlackNotification.post(post_options)
    true
  end





end

app/controllers/audit_logs_controller.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file
class AuditLogsController < ApplicationController

  def index
    @pagination_params = {}
    @filter_strings = []
    @filtered = false

    if(params[:contributor_id] and @contributor = Contributor.find_by_id(params[:contributor_id]))
      @pagination_params[:contributor_id] = params[:contributor_id]
      @filter_strings << "Contributor: #{@contributor.fullname}"
      @filtered = true
      audit_log_scope = @contributor.audit_logs
    else
      audit_log_scope = AuditLog.scoped({})
    end

    @audit_logs = audit_log_scope.order("created_at desc").page(params[:page]).per(25)

  end

  def show
    @audit_log = AuditLog.find(params[:id])
  end



end

app/views/audit_logs/index.html.erb
<h1>Audit Logs</h1>
<%- if @filter_strings -%>
<p>Filtered by: <%= @filter_strings.join(' | ') -%></p>
<%- end -%>
<div id="paginator_wrapper">
  <%- if @audit_logs.length > 0 -%>
    <p class="display_results">Displaying <strong><%= @audit_logs.offset_value + 1 %>-<%= @audit_logs.offset_value + @audit_logs.length %></strong> of <strong><%= @audit_logs.total_count %></strong></p>
  <%- else -%>
      <p class="display_results">Displaying <strong>0</strong> of <strong>0</strong></p>
  <%- end -%>
  <%= paginate @audit_logs, :params => @pagination_params %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID#</th>
      <th>Who</th>
      <th>Audited Item</th>
      <th>Action</th>
      <th>When</th>
    </tr>
  </thead>
  <tbody>
    <%- @audit_logs.each do |audit_log| -%>
      <tr>
        <td><%= audit_log.id -%> (<%= link_to('details',audit_log_path(audit_log.id)) -%>)</td>
        <td><%= link_to(audit_log.contributor.fullname,audit_logs_path(:contributor_id => audit_log.contributor.id)) -%></td>
        <td><%= audit_log_itemlink(audit_log) -%></td>
        <td><%= audit_log.audit_action_string -%></td>
        <td><%= audit_log.created_at.to_s -%></td>
      </tr>
    <%- end -%>
    </tbody>
  </table>

app/views/audit_logs/show.html.erb
<h1>Audit Details for Audit# <%= @audit_log.id -%></h1>
<div class="row">
  <div class="col-md-12">
    <table class="table">
        <tr>
          <td>Who</td>
          <td><%= link_to(@audit_log.contributor.fullname,audit_logs_path(:contributor_id => @audit_log.contributor.id)) -%></td>
        </tr>
        <tr>
          <td>When</td>
          <td><%= @audit_log.created_at.to_s -%></td>
        </tr>
        <tr>
      		<td>Audit Type</td>
        	<td><%= @audit_log.audit_type -%></td>
        </tr>
        <tr>
            <td>Audited Item</td>
            <td><%= audit_log_itemlink(@audit_log) -%></td>
        </tr>
        <tr>
            <td>Action</td>
            <td><%= @audit_log.audit_action_string -%></td>
        </tr>
        <%- if(@audit_log.changed_item == 'notes') -%>
          <tr>
            <td>Previous Notes</td>
            <td><%= (@audit_log.previous_notes.blank? ? 'n/a' : @audit_log.previous_notes.html_safe) -%></td>
          </tr>
          <tr>
            <td>Current Notes</td>
            <td><%= (@audit_log.current_notes.blank? ? 'n/a' : @audit_log.current_notes.html_safe) -%></td>
          </tr>
        <%- elsif(@audit_log.changed_item == 'copyright') -%>
          <tr>
            <td>Previous Copyright</td>
            <td><%= (@audit_log.previous_notes.blank? ? 'n/a' : @audit_log.previous_notes.html_safe) -%></td>
          </tr>
          <tr>
            <td>Current Copyright</td>
            <td><%= (@audit_log.current_notes.blank? ? 'n/a' : @audit_log.current_notes.html_safe) -%></td>
          </tr>
        <%- end -%>
    </table>
  </div>
</div>