config/routes.rb
Imageaudit::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      post :change_keeppublished
      post :set_notes
      put :set_notes
    end
  end

  resources :communities, :only => [:index, :show]
  resources :audit_logs, :only => [:index, :show]

  resources :images, :only => [:index, :show] do
    member do
      post :change_stock
      post :change_communityreview
      post :change_staffreview
      post :set_notes
      put :set_notes
    end
  end

  match '/bulk_change_stock_and_staff_review', to: 'images#bulk_change_stock_and_staff_review'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

end

app/models/page.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file

class Page < ActiveRecord::Base
  include CacheTools
  include MarkupScrubber
  has_many :year_analytics
  has_many :page_taggings
  has_many :tags, :through => :page_taggings
  has_many :group_pages
  has_many :groups, :through => :group_pages
  has_many :linkings, dependent: :destroy
  has_many :links, :through => :linkings
  has_many :page_hosted_images
  has_many :hosted_images, :through => :page_hosted_images

  belongs_to :keep_published_reviewer,  :class_name => "Contributor", :foreign_key => "keep_published_by"
  belongs_to :community_reviewer,  :class_name => "Contributor", :foreign_key => "community_reviewed_by"
  belongs_to :staff_reviewer,      :class_name => "Contributor", :foreign_key => "staff_reviewed_by"


  # index settings
  NOT_INDEXED = 0
  INDEXED = 1
  NOT_GOOGLE_INDEXED = 2

  # hardcoded right now
  START_DATE = Date.parse('2014-08-24')
  END_DATE = Date.parse('2015-08-22')

  PERCENTILES = [99,95,90,75,50,25,10]
  DATATYPES = ['Article','Faq']

  scope :articles, where(:datatype => 'Article')
  scope :faqs, where(:datatype => 'Faq')
  scope :created_since, lambda{|date| where("#{self.table_name}.created_at >= ?",date)}
  scope :from_create, where(:source => 'create')

  scope :eligible_pages, -> {where("weeks_published > 0")}
  scope :viewed, -> (view_base = 1) {eligible_pages.where("mean_unique_pageviews >= ?",view_base)}
  scope :unviewed, -> (view_base = 1) {eligible_pages.where("mean_unique_pageviews < ?",view_base)}
  scope :missing, -> {eligible_pages.where("mean_unique_pageviews = 0")}

  scope :tagged_with, lambda{|tagliststring|
    tag_list = Tag.castlist_to_array(tagliststring)
    in_string = tag_list.map{|t| "'#{t}'"}.join(',')
    joins(:tags).where("tags.name IN (#{in_string})").group("#{self.table_name}.id").having("COUNT(#{self.table_name}.id) = #{tag_list.size}")
  }

  scope :tagged_with_any, lambda { |tagliststring|
    tag_list = Tag.castlist_to_array(tagliststring)
    in_string = tag_list.map{|t| "'#{t}'"}.join(',')
    joins(:tags).where("tags.name IN (#{in_string})").group("#{self.table_name}.id")
  }

  def self.eligible(flag = true)
    if(flag)
      where("weeks_published > 0")
    else
      where("weeks_published = 0")
    end
  end

  def self.viewed(flag = true)
    if(flag)
      eligible.where("mean_unique_pageviews >= 1")
    else
      eligible.where("mean_unique_pageviews < 1")
    end
  end

  def self.missing
    eligible.where("mean_unique_pageviews = 0")
  end

  def self.keep(flag = true)
    if(flag)
      where("keep_published = 1")
    else
      where("keep_published = 0")
    end
  end

  def display_title(options = {})
    truncate_it = options[:truncate].nil? ? true : options[:truncate]

    if(self.title.blank?)
      display_title = '(blank)'
    elsif(truncate_it)
      display_title = self.title.truncate(80, :separator => ' ')
    else
      display_title = self.title
    end
    display_title
  end

  def self.find_by_title_url(url)
   return nil unless url
   real_title = url.gsub(/_/, ' ')
   self.find_by_title(real_title)
  end

  def self.update_from_articles
    article_database = ArticlePage.connection.current_database
    query = <<-END_SQL.gsub(/\s+/, " ").strip
    INSERT INTO #{self.connection.current_database}.#{self.table_name} (id, datatype, title, source_created_at, source_updated_at, source, source_url, article_created_at, article_updated_at,created_at,updated_at)
    SELECT id, datatype, title, source_created_at, source_updated_at, source, source_url, created_at, updated_at, NOW(), NOW()
    FROM #{article_database}.pages
    ON DUPLICATE KEY UPDATE
    datatype = #{article_database}.pages.datatype,
    title = #{article_database}.pages.title,
    source_created_at = #{article_database}.pages.source_created_at,
    source_updated_at = #{article_database}.pages.source_updated_at,
    source = #{article_database}.pages.source,
    source_url = #{article_database}.pages.source_url,
    article_created_at = #{article_database}.pages.created_at,
    article_updated_at = #{article_database}.pages.updated_at
    END_SQL
    self.connection.execute(query)
    true
  end

  def self.remove_deleted_pages
    article_database = ArticlePage.connection.current_database
    page_list = self.joins("LEFT join #{article_database}.pages on #{article_database}.pages.id = #{self.connection.current_database}.#{self.table_name}.id")
                    .where("#{article_database}.pages.id IS NULL")
                    .select("#{self.connection.current_database}.#{self.table_name}.*")
    page_list.each do |p|
      p.destroy
    end
    true
  end

  def self.tag_counts(cache_options= {})
    cache_key = self.get_cache_key(__method__)
    Rails.cache.fetch(cache_key,cache_options) do
      joins(:tags).group('tags.id').order('count_all DESC').count
    end
  end

  def self.counts_by_group_for_datatype(datatype,cache_options= {})
    cache_key = self.get_cache_key(__method__,{datatype: datatype})
    Rails.cache.fetch(cache_key,cache_options) do
      pagecounts = {}
      pagecounts['all'] = Page.by_datatype(datatype).count
      Group.launched.each do |group|
        pagecounts[group.id] = group.pages.by_datatype(datatype).count
      end
      pagecounts
    end
  end

  def weeks_published(through_date = Page::END_DATE)
    if(self.article_created_at.to_date > through_date)
      0
    else
      ((through_date - self.article_created_at.to_date).to_i / 7).to_i
    end
  end

  def page_stat_attributes
    pageviews = self.year_analytics.pluck(:pageviews).sum
    unique_pageviews = self.year_analytics.pluck(:unique_pageviews).sum
    weeks_published = self.weeks_published(Page::END_DATE)
    if(weeks_published > 52)
      mean_pageviews = pageviews / 52.to_f
      mean_unique_pageviews = unique_pageviews / 52.to_f
    elsif(weeks_published > 0)
      mean_pageviews = pageviews / weeks_published.to_f
      mean_unique_pageviews = unique_pageviews / weeks_published.to_f
    else
      mean_pageviews = 0
      mean_unique_pageviews = 0
    end

    attributes = {}
    attributes[:unique_pageviews] = unique_pageviews
    attributes[:weeks_published] = weeks_published
    attributes[:mean_unique_pageviews] = mean_unique_pageviews
    attributes[:image_links] = self.links.image.count
    attributes[:hosted_image_count] = self.hosted_images.count
    attributes
  end

  def self.overall_stat_attributes(cache_options = {})
    # cache_key = self.get_cache_key(__method__)
    # Rails.cache.fetch(cache_key,cache_options) do
      overall_stats = {}
      overall_stats['total_pages'] =  self.count
      overall_stats['eligible_pages'] = self.eligible_pages.count
      overall_stats['viewed_pages'] = self.viewed.count
      overall_stats['image_links'] = Link.image.count("distinct links.id")
      overall_stats['hosted_images'] = HostedImage.linked.count
      overall_stats['stock_hosted_images'] = HostedImage.linked.stock('Yes').count
      overall_stats['unreviewed_stock_hosted_images'] = HostedImage.linked.stock('Unreviewed').count
      overall_stats['staff_reviewed_hosted_images'] = HostedImage.linked.staff_reviewed('Reviewed').count
      overall_stats['staff_unreviewed_hosted_images'] = HostedImage.linked.staff_reviewed('Unreviewed').count
      overall_stats['staff_complete_hosted_images'] = HostedImage.linked.staff_reviewed('Complete').count
      overall_stats['staff_incomplete_hosted_images'] = HostedImage.linked.staff_reviewed('Incomplete').count
      overall_stats
    # end
  end

  def self.mup_percentiles
    mups = self.pluck(:mean_unique_pageviews)
    viewed_percentiles = []
    PERCENTILES.each do |percentile|
      viewed_percentiles << mups.nist_percentile(percentile)
    end
    viewed_percentiles
  end

  def update_stats
    self.update_attributes(self.page_stat_attributes)
  end

  def self.rebuild_stats
    # get stat sets
    unique_pageviews_set = Page.joins(:year_analytics).group('year_analytics.page_id').sum('year_analytics.unique_pageviews')
    image_link_set = Page.joins(:links).where('links.linktype = ?',Link::IMAGE).group('pages.id').count
    hosted_image_set = Page.joins(:hosted_images).group('pages.id').count
    self.find_in_batches(:batch_size => 100) do |page_group|
      update_statement_set = []
      page_group.each do |page|
        weeks_published = page.weeks_published
        hosted_image_count = (hosted_image_set[page.id].nil? ? 0 : hosted_image_set[page.id])
        unique_pageviews = (unique_pageviews_set[page.id].nil? ? 0 : unique_pageviews_set[page.id])
        if(weeks_published > 52)
          mean_unique_pageviews = ( unique_pageviews / 52.to_f )
        elsif(weeks_published > 0)
          mean_unique_pageviews = ( unique_pageviews / weeks_published.to_f )
        else
          mean_unique_pageviews = 0
        end
        image_links  = (image_link_set[page.id].nil? ? 0 : image_link_set[page.id])
        # custom build update statement
        query = <<-END_SQL.gsub(/\s+/, " ").strip
        UPDATE #{self.table_name}
        SET
          unique_pageviews = #{unique_pageviews},
          hosted_image_count = #{hosted_image_count},
          weeks_published = #{weeks_published},
          image_links = #{image_links},
          mean_unique_pageviews = #{mean_unique_pageviews},
          updated_at = NOW()
        WHERE id = #{page.id}
        END_SQL
        update_statement_set << query
      end
      self.transaction do
        update_statement_set.each do |statement|
          self.connection.execute(statement)
        end
      end
    end
    true
  end


end

app/models/tag.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file

class Tag < ActiveRecord::Base
  has_many :analytics
  has_many :page_taggings
  has_many :pages, :through => :page_taggings
  has_many :analytics, :through => :pages
  belongs_to :group

  scope :grouptags, where("group_id > 0")

  SPLITTER = Regexp.new(/\s*,\s*/)
  JOINER = ", "

  # normalize tag names
  # convert whitespace to single space, underscores to space, Yank everything that's not alphanumeric except colon, hyphen, or whitespace (which is now single spaces)
  def self.normalizename(name)
    # make an initial downcased copy - don't want to modify name as a side effect
    returnstring = name.downcase
    # now, use the replacement versions of gsub and strip on returnstring
    # convert underscores to spaces
    returnstring.gsub!('_',' ')
    # get rid of anything that's not a "word", not space, not : and not -
    returnstring.gsub!(/[^\w :-]/,'')
    # reduce multiple spaces to a single space
    returnstring.gsub!(/ +/,' ')
    # remove leading and trailing whitespace
    returnstring.strip!
    returnstring
  end

  def self.rebuild
    self.connection.execute("truncate table #{self.table_name};")
    ArticleTag.find_in_batches do |group|
      insert_values = []
      group.each do |tag|
        insert_list = []
        insert_list << tag.id
        insert_list << ActiveRecord::Base.quote_value(tag.name)
        insert_list << ActiveRecord::Base.quote_value(tag.created_at.to_s(:db))
        insert_values << "(#{insert_list.join(',')})"
      end
      insert_sql = "INSERT INTO #{self.table_name} (id,name,created_at) VALUES #{insert_values.join(',')};"
      self.connection.execute(insert_sql)
    end

    # set groups
    ArticleTag.community_resource_tags.each do |community_tag|
      if(tag_group = community_tag.article_communities.first)
        group_id = tag_group.id
        update_sql = "UPDATE #{self.table_name} SET group_id = #{group_id} WHERE #{self.table_name}.id = #{community_tag.id}"
        self.connection.execute(update_sql)
      end
    end
    true
  end

  def self.pagetags_for_group(group)
    idlist = group.pages.pluck('pages.id')
    self.where('group_id IS NULL').joins(:page_taggings).where("page_taggings.page_id IN (#{idlist.join(',')})")
  end


  def self.castlist_to_array(obj,normalizestring=true,processnots=false)
    returnarray = []
    if(processnots)
      returnnotarray = []
    end

    case obj
      when Array
        obj.each do |item|
          case item
            when /^\d+$/, Fixnum then returnarray << Tag.find(item).name # This will be slow if you use ids a lot.
            when Tag then returnarray << item.name
            when String
              if(processnots and item.starts_with?('!'))
                returnnotarray << (normalizestring ? Tag.normalizename(item) : item.strip)
              else
                returnarray << (normalizestring ? Tag.normalizename(item) : item.strip)
              end
            else
              raise "Invalid type"
          end
        end
      when String
        obj.split(Tag::SPLITTER).each do |tag_name|
          if(!tag_name.empty?)
            if(processnots and tag_name.starts_with?('!'))
              returnnotarray << (normalizestring ? Tag.normalizename(tag_name) : tag_name.strip)
            else
              returnarray << (normalizestring ? Tag.normalizename(tag_name) : tag_name.strip)
            end
          end
        end
      else
        raise "Invalid object of class #{obj.class} as tagging method parameter"
    end

    returnarray.flatten!
    returnarray.compact!
    returnarray.uniq!


    if(processnots)
      returnnotarray.flatten!
      returnnotarray.compact!
      returnnotarray.uniq!
      return [returnarray,returnnotarray]
    else
      return returnarray
    end
  end

end

app/views/pages/_keep_page.html.erb
<div class="dashmodule">
  <%- if @page.keep_published.nil? -%>
    <p><strong>Keep Page Published:</strong> <span class="label label-info">Not Yet Reviewed</span></p>
    <p>
      <%= link_to('Keep page published',change_keeppublished_page_path({id: @page.id, keep_published: 'yes'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
      <%= link_to('Do not keep page published',change_keeppublished_page_path({id: @page.id, keep_published: 'no'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- elsif @page.keep_published? -%>
    <p><strong>Keep Page Published:</strong> <span class="label label-success">YES</span></p>
    <p><small>Keep published review from <%= @page.keep_published_reviewer.fullname -%></small></p>
    <p>
    <%= link_to('Do not keep page published',change_keeppublished_page_path({id: @page.id, keep_published: 'no'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- else -%>
    <p><strong>Keep Page Published:</strong> <span class="label label-warning">NO</span></p>
    <p><small>Keep published review from <%= @page.keep_published_reviewer.fullname -%></small></p>
    <p>
    <%= link_to('Keep page published',change_keeppublished_page_path({id: @page.id, keep_published: 'yes'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- end -%>
</div>

app/views/pages/_page_audit_notes.html.erb
<div class='page_notes'>
<%- if(page.notes.present?) -%>
  <%= page.notes.html_safe %>
<%- else -%>
    <p><em>No notes provided</em></p>
<%- end -%>

<%- if @currentcontributor -%>
  <p id="edit_notes_link_for_page_<%= @page.id %>"><small><%= link_to('edit','#',id: "edit_notes_for_page_#{@page.id}") %></small></p>
<%- end -%>

<script class="code" type="text/javascript">
  $('#edit_notes_for_page_<%= @page.id %>').click(function() {
    $('#edit_notes_link_for_page_<%= @page.id %>').hide();
    $('#notes_for_page_<%= @page.id %>').html('<%= escape_javascript(render(partial: "page_audit_notes_form", locals: {page: @page})) %>');
 });
</script>
</div>

app/views/pages/_page_audit_notes_form.html.erb
<%= form_for(page, :url => set_notes_page_path(id: page.id), remote: true, html: {id: "notes_form_for_page_#{page.id}"}) do |f| %>

  <div class="form-group">
    <fieldset>
      <%= f.text_area :notes, "rows" => 5, class: 'col-md-8', id: "page_notes_field_#{page.id}" %>
    </fieldset>
  </div>

  <p>
    <%= f.submit "Save Changes", :class => "btn btn-primary" -%>
    <%= f.submit('cancel', :class => 'btn btn-link') -%>
  </p>

<%- end -%>

<script class="code" type="text/javascript">
  $('#page_notes_field_<%= page.id %>').wysihtml5({toolbar: { "fa": true, "link": false, "image": false}});
</script>

app/views/pages/change_keep_page.js.erb
$("#keeppage").html("<%= escape_javascript(render(:partial => 'keep_page')) %>")

app/views/pages/change_keeppublished.js.erb
$("#keeppage").html("<%= escape_javascript(render(:partial => 'keep_page')) %>")

app/views/pages/index.html.erb
<h1>Pages</h1>
<div class="row">
  <div class="col-md-8">
<%- if @filter_strings -%>
<p>Filtered by: <%= @filter_strings.join(' | ') -%></p>
<%- end -%>

<div id="paginator_wrapper">
  <%- if @pages.length > 0 -%>
    <p class="display_results">Displaying <strong><%= @pages.offset_value + 1 %>-<%= @pages.offset_value + @pages.length %></strong> of <strong><%= @pages.total_count %></strong></p>
  <%- else -%>
      <p class="display_results">Displaying <strong>0</strong> of <strong>0</strong></p>
  <%- end -%>
  <%= paginate @pages, :params => @pagination_params %>
</div>
</div>
<%- if(!@community.nil?) -%>
  <div class="col-md-3">
  <p><%= link_to("<i class='fa fa-file-o'></i> Download this list (.csv)".html_safe,
              pages_path(@pagination_params.merge(download: 'csv')),
              :class => 'btn btn-primary') %></p>
<p><em>Downloads can take about 10 seconds for every 500 pages to generate, it may take a minute or two after you
  press the button for the file to start downloading</em></p>
</div>
<%- end -%>
</div>
</div>
<div class="row">
  <div class="col-md-12">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Page ID#</th>
      <th>Keep Published?</th>
      <th>Page Title</th>
      <th>Total Unique Pageviews</th>
      <th>Mean Unique Pageviews</th>
      <th>Hosted Images</th>
      <th>Hosted Imagelist</th>
    </tr>
  </thead>
  <tbody>
    <%- @pages.each do |page| -%>
      <tr>
        <td><%= page.id -%> (<%= link_to('details',page_path(page.id)) -%>)</td>
        <td>
          <%- if page.keep_published.nil? -%>
            <span class="label label-info">not reviewed</span>
          <%- elsif page.keep_published? -%>
            <span class="label label-success">Yes</span>
          <%- else -%>
            <span class="label label-warning">No</span>
          <%- end -%>
        </td>
        <td><%= page.title -%> (<%= pageinfo_link(page.id,'page info') -%>)</td>
        <td><%= number_with_delimiter(page.unique_pageviews) -%></td>
        <td><%= number_with_precision(page.mean_unique_pageviews, precision: 2) -%></td>
        <td> <%= page.hosted_image_count -%></td>
        <td>
            <%- page.hosted_image_ids.each do |hid| -%>
              <%= link_to("#{hid}",image_path(hid)) -%>,
            <%- end -%>
        </td>
      </tr>
    <%- end -%>
    </tbody>
  </table>
  <div id="paginator_wrapper">
    <%- if @pages.length > 0 -%>
      <p class="display_results">Displaying <strong><%= @pages.offset_value + 1 %>-<%= @pages.offset_value + @pages.length %></strong> of <strong><%= @pages.total_count %></strong></p>
    <%- else -%>
        <p class="display_results">Displaying <strong>0</strong> of <strong>0</strong></p>
    <%- end -%>
    <%= paginate @pages, :params => @pagination_params %>
  </div>
</div>
</div>

app/views/pages/set_notes.js.erb
$("#notes_for_page_<%= @page.id %>").html("<%= escape_javascript(render partial: 'page_audit_notes', locals: {page: @page}) %>");
$('#edit_notes_link_for_page_<%= @page.id %>').show();

app/views/pages/show.html.erb
<h1>Page Details for Page ID# <%= @page.id -%></h1>
<p><%= @page.title %></p>
<div class="row">
  <div class="col-md-6">
<table class="table">
    <tr>
      <td>Original Page Type</td>
      <td class="mednumber"><%= @page.datatype -%></td>
    </tr>
    <tr>
  		<td>Weeks Published</td>
    	<td class="mednumber"><%= @page.weeks_published -%></td>
    </tr>
    <tr>
      <td>Unique Pageviews<br/>
      <em>between <%= Page::START_DATE -%> and <%= Page::END_DATE -%></em></td>
      <td class="mednumber"><%= number_with_delimiter(@page.unique_pageviews) -%></td>
    </tr>
    <tr>
      <td>Mean Unique Pageviews<br/>
      <em>between <%= Page::START_DATE -%> and <%= Page::END_DATE -%></em></td>
      <td class="mednumber"><%= number_with_precision(@page.mean_unique_pageviews,precision: 2) -%></td>
    </tr>
    <tr>
      <td>Hosted Images<br/>
      <td class="mednumber"><%= number_with_delimiter(@page.hosted_image_count) -%></td>
    </tr>
    <tr>
        <td>Communities</td>
        <td>
          <%- @page.groups.publishing.each do |pc| -%>
          <%= link_to(pc.name,community_path(pc.id)) -%><br/>
          <%- end -%>
        </td>
    </tr>
    <tr>
        <td>Source</td>
        <td><%= @page.source %></td>
    </tr>
    <tr>
        <td>Source URL</td>
        <td><%= link_to(@page.source_url, @page.source_url)%></td>
    </tr>
    <tr>
        <td>Source Page Created At</td>
        <td><%= @page.source_created_at.to_s -%></td>
    </tr>
    <tr>
        <td>Source Page Last Updated At</td>
        <td><%= @page.source_updated_at.to_s -%></td>
    </tr>
    <tr>
      <td><%= pageinfo_link(@page.id,'More page details...') %></td>
      <td>&nbsp;</td>
    </tr>
</table>
</div>

<div class="col-md-6 text-center">
  <div id="keeppage">
    <%= render(partial: 'keep_page') -%>
  </div>
</div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading"
      <h3 class="panel-title">Page Notes</h3>
      </div>
      <div class="panel-body">
        <div id='notes_for_page_<%= @page.id %>'>
          <%= render(partial: 'page_audit_notes', locals: {page: @page}) %>
        </div>
      </div>
    </div>
  </div>
</div>


<%- if @page.hosted_image_count > 0 -%>
<h2>Hosted Images</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID#</th>
      <th>Image</th>
      <th>Pages</th>
      <th>Source</th>
      <th>Stock?</th>
      <th>Copyright</th>
      <th>Copyright Reviewed?</th
    </tr>
  </thead>
  <tbody>
    <%- @page.hosted_images.each do |image| -%>
      <tr>
        <td><%= image.id -%> (<%= link_to('details',image_path(image.id)) -%>)</td>
        <td><%= imageaudit_link(image) -%></td>
        <td>
            <%- image.page_ids.each do |pid | -%>
              <%= link_to("#{pid}",page_path(pid)) -%>,
            <%- end -%>
        </td>
        <td><%= imageaudit_sourcelink(image) -%>
        <%- if(image.source == 'create' and image.original_wiki?) -%>
          <br/><em> originally copwiki </em>
        <%- end -%>
        </td>
        <td>
          <%- if image.is_stock.nil? -%>
            <span class="label label-info">not reviewed</span>
          <%- elsif image.is_stock? -%>
            <span class="label label-warning">Yes</span>
          <%- else -%>
            <span class="label label-warning">No</span>
          <%- end -%>
        </td>
        <td><%= image.copyright -%></td>
        <td>
            Community:
            <%- if image.community_reviewed.nil? -%>
              <span class="label label-info">not reviewed</span>
            <%- elsif image.community_reviewed? -%>
              <span class="label label-success">Complete</span>
            <%- else -%>
              <span class="label label-warning">Incomplete</span>
            <%- end -%>
            <br/>
            Staff:
            <%- if image.staff_reviewed.nil? -%>
              <span class="label label-info">not reviewed</span>
            <%- elsif image.staff_reviewed? -%>
              <span class="label label-success">Complete</span>
            <%- else -%>
              <span class="label label-warning">Incomplete</span>
            <%- end -%>
        </td>
      </tr>
    <%- end -%>
    </tbody>
  </table>
<%- end -%>