config/routes.rb
Imageaudit::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      post :change_keeppublished
      post :set_notes
      put :set_notes
    end
  end

  resources :communities, :only => [:index, :show]
  resources :audit_logs, :only => [:index, :show]

  resources :images, :only => [:index, :show] do
    member do
      post :change_stock
      post :change_communityreview
      post :change_staffreview
      post :set_notes
      put :set_notes
    end
  end

  match '/bulk_change_stock_and_staff_review', to: 'images#bulk_change_stock_and_staff_review'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

end

app/controllers/communities_controller.rb
# === COPYRIGHT:
# Copyright (c) North Carolina State University
# Developed with funding from the eXtension Foundation
# === LICENSE:
#
# see LICENSE file
class CommunitiesController < ApplicationController

  def index
    @group_stats = Group.stats_by_group.sort_by{|id,data| data['group_name']} 
  end

  def show
    @community = Group.find(params[:id])
    @summary_data = @community.page_stat_attributes
  end

end

app/views/communities/index.html.erb
<h1>Communities</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Community Name</th>
      <th>Total Pages</th>
      <th>Viewed Pages (%)</th>
      <th>Unviewed Pages (%)</th>
      <th>Hosted Images</th>
      <th>Stock Unreviewed</th>
      <th>Copyright complete</th>
      <th>Copyright incomplete</th>
      <th>Copyright not yet reviewed</th>
    </tr>
  </thead>
  <tbody>
    <%- @group_stats.each do |group_id, stats| -%>
        <tr>
        <td><%= link_to(stats['group_name'],community_path(group_id)) -%></td>
        <%- if stats['total_pages'] == 0 -%>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
        <%- else -%>
          <td><%= number_with_delimiter(stats['total_pages']) -%></td>
          <td>
            <%= number_with_delimiter(stats['viewed_pages']) -%>
            (<%= percentage_display(stats['viewed_pages'],stats['eligible_pages']) -%>)
          </td>
          <td>
            <%= number_with_delimiter((stats['eligible_pages'] - stats['viewed_pages']) ) -%>
            (<%= percentage_display((stats['eligible_pages'] - stats['viewed_pages']),stats['eligible_pages']) -%>)
          </td>
          <td><%= number_with_delimiter(stats['hosted_images']) -%></td>
          <td><%= number_with_delimiter(stats['unreviewed_stock_hosted_images']) -%></td>
          <td><%= number_with_delimiter(stats['staff_complete_hosted_images']) -%></td>
          <td><%= number_with_delimiter(stats['staff_incomplete_hosted_images']) -%></td>
          <td><%= number_with_delimiter(stats['staff_unreviewed_hosted_images']) -%></td>
        <%- end -%>
        </tr>
      <%- end -%>
    </tbody>
  </table>

app/views/communities/show.html.erb
<h1><%= @community.name -%> Content Summary</h1>
<h1>Content Summary</h1>
<table class="table table-striped">
    <tr>
  		<td>Total Pages</td>
    	<td class="mednumber"><%= link_to(number_with_delimiter(@summary_data['total_pages']), pages_path(:community_id => @community.id)) -%></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>Eligible Pages</td>
      <td class="mednumber"><%= link_to(number_with_delimiter(@summary_data['eligible_pages']), pages_path(:community_id => @community.id,:page_status => 'Eligible')) -%></td>
      <td><em>Pages published for at least 1 week prior to <%= Page::END_DATE -%></em></td>
    </tr>
    <tr>
      <td>Viewed Pages</td>
      <td style="white-space:nowrap;">
        <span class="mednumber"><%= link_to(number_with_delimiter(@summary_data['viewed_pages']), pages_path(:community_id => @community.id,:page_status => 'Viewed')) -%></span>
        <span class="mednumber">(<%= percentage_display(@summary_data['viewed_pages'],@summary_data['eligible_pages']) -%>)</span>
      </td>
      <td><em>Pages with <strong>at least one or more</strong> mean unique pageviews per week<br/>between <%= Page::START_DATE -%> and <%= Page::END_DATE -%></em></td>
    </tr>
    <tr>
      <td>Unviewed Pages</td>
      <td style="white-space:nowrap;">
        <span class="mednumber"><%= link_to(number_with_delimiter((@summary_data['eligible_pages'] - @summary_data['viewed_pages']) ), pages_path(:community_id => @community.id,:page_status => 'Unviewed')) -%></span>
        <span class="mednumber">(<%= percentage_display((@summary_data['eligible_pages'] - @summary_data['viewed_pages']),@summary_data['eligible_pages']) -%>)</span>
      </td>
      <td>
        <em>Pages with <strong>less than one</strong> mean unique pageview per week<br/>
        between <%= Page::START_DATE -%> and <%= Page::END_DATE -%></em>
      </td>
    </tr>

</table>
<h3>Image Statistics</h3>
<table class="table">
  <tr>
    <td>Hosted Images</td>
    <td>
      <span class="mednumber"><%= link_to(number_with_delimiter(@summary_data['hosted_images']), images_path(:community_id => @community.id)) -%></span><br/>
    </td>
    <td>
      <em>Images uploaded to either the legacy cop.extension.org cms or the create.extension.org cms</em>
    </td>
  </tr>

  <tr>
    <td>Images - Unreviewed for Stock</td>
    <td>
      <span class="mednumber"><%= link_to(number_with_delimiter(@summary_data['unreviewed_stock_hosted_images']), images_path(:community_id => @community.id,:stock => 'Unreviewed')) -%></span><br/>
    </td>
    <td>
      <em>Images that have been reviewed as a stock image by eXtension Core Team members or the Community</em>
    </td>
  </tr>

  <tr>
    <td>Staff Copyright Complete Images</td>
    <td>
      <span class="mednumber"><%= link_to(number_with_delimiter(@summary_data['staff_complete_hosted_images']), images_path(:community_id => @community.id,:staff_reviewed => 'Complete')) -%></span><br/>
    </td>
    <td>
      <em>Images that have been reviewed by an eXtension Staff member as copyright complete</em>
    </td>
  </tr>

  <tr>
    <td>Staff Copyright Incomplete Images</td>
    <td>
      <span class="mednumber"><%= link_to(number_with_delimiter(@summary_data['staff_incomplete_hosted_images']), images_path(:community_id => @community.id,:staff_reviewed => 'Incomplete')) -%></span><br/>
    </td>
    <td>
      <em>Images that have been reviewed by an eXtension Staff member as copyright <strong>incomplete</strong></em>
    </td>
  </tr>


  <tr>
    <td>Images - Unreviewed by Staff for Copyright</td>
    <td>
      <span class="mednumber"><%= link_to(number_with_delimiter(@summary_data['staff_unreviewed_hosted_images']), images_path(:community_id => @community.id,:staff_reviewed => 'Unreviewed')) -%></span><br/>
    </td>
    <td>
      <em>Images that have not yet had a copyright review from an eXtension Staff member</em>
    </td>
  </tr>

</table>