config/routes.rb
Imageaudit::Application.routes.draw do
  root :to => 'home#index'
  resources :pages, :only => [:index, :show] do
    member do
      post :change_keeppublished
      post :set_notes
      put :set_notes
    end
  end

  resources :communities, :only => [:index, :show]
  resources :audit_logs, :only => [:index, :show]

  resources :images, :only => [:index, :show] do
    member do
      post :change_stock
      post :change_communityreview
      post :change_staffreview
      post :set_notes
      put :set_notes
    end
  end

  match '/bulk_change_stock_and_staff_review', to: 'images#bulk_change_stock_and_staff_review'

  # authentication
  match '/logout', to:'auth#end', :as => 'logout'
  match '/auth/:provider/callback', to: 'auth#success'

end

app/models/tag.rb
# === COPYRIGHT:
#  Copyright (c) North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#
#  see LICENSE file

class Tag < ActiveRecord::Base
  has_many :analytics
  has_many :page_taggings
  has_many :pages, :through => :page_taggings
  has_many :analytics, :through => :pages
  belongs_to :group

  scope :grouptags, where("group_id > 0")

  SPLITTER = Regexp.new(/\s*,\s*/)
  JOINER = ", "

  # normalize tag names
  # convert whitespace to single space, underscores to space, Yank everything that's not alphanumeric except colon, hyphen, or whitespace (which is now single spaces)
  def self.normalizename(name)
    # make an initial downcased copy - don't want to modify name as a side effect
    returnstring = name.downcase
    # now, use the replacement versions of gsub and strip on returnstring
    # convert underscores to spaces
    returnstring.gsub!('_',' ')
    # get rid of anything that's not a "word", not space, not : and not -
    returnstring.gsub!(/[^\w :-]/,'')
    # reduce multiple spaces to a single space
    returnstring.gsub!(/ +/,' ')
    # remove leading and trailing whitespace
    returnstring.strip!
    returnstring
  end

  def self.rebuild
    self.connection.execute("truncate table #{self.table_name};")
    ArticleTag.find_in_batches do |group|
      insert_values = []
      group.each do |tag|
        insert_list = []
        insert_list << tag.id
        insert_list << ActiveRecord::Base.quote_value(tag.name)
        insert_list << ActiveRecord::Base.quote_value(tag.created_at.to_s(:db))
        insert_values << "(#{insert_list.join(',')})"
      end
      insert_sql = "INSERT INTO #{self.table_name} (id,name,created_at) VALUES #{insert_values.join(',')};"
      self.connection.execute(insert_sql)
    end

    # set groups
    ArticleTag.community_resource_tags.each do |community_tag|
      if(tag_group = community_tag.article_communities.first)
        group_id = tag_group.id
        update_sql = "UPDATE #{self.table_name} SET group_id = #{group_id} WHERE #{self.table_name}.id = #{community_tag.id}"
        self.connection.execute(update_sql)
      end
    end
    true
  end

  def self.pagetags_for_group(group)
    idlist = group.pages.pluck('pages.id')
    self.where('group_id IS NULL').joins(:page_taggings).where("page_taggings.page_id IN (#{idlist.join(',')})")
  end


  def self.castlist_to_array(obj,normalizestring=true,processnots=false)
    returnarray = []
    if(processnots)
      returnnotarray = []
    end

    case obj
      when Array
        obj.each do |item|
          case item
            when /^\d+$/, Fixnum then returnarray << Tag.find(item).name # This will be slow if you use ids a lot.
            when Tag then returnarray << item.name
            when String
              if(processnots and item.starts_with?('!'))
                returnnotarray << (normalizestring ? Tag.normalizename(item) : item.strip)
              else
                returnarray << (normalizestring ? Tag.normalizename(item) : item.strip)
              end
            else
              raise "Invalid type"
          end
        end
      when String
        obj.split(Tag::SPLITTER).each do |tag_name|
          if(!tag_name.empty?)
            if(processnots and tag_name.starts_with?('!'))
              returnnotarray << (normalizestring ? Tag.normalizename(tag_name) : tag_name.strip)
            else
              returnarray << (normalizestring ? Tag.normalizename(tag_name) : tag_name.strip)
            end
          end
        end
      else
        raise "Invalid object of class #{obj.class} as tagging method parameter"
    end

    returnarray.flatten!
    returnarray.compact!
    returnarray.uniq!


    if(processnots)
      returnnotarray.flatten!
      returnnotarray.compact!
      returnnotarray.uniq!
      return [returnarray,returnnotarray]
    else
      return returnarray
    end
  end

end

app/controllers/images_controller.rb
# === COPYRIGHT:
# Copyright (c) North Carolina State University
# Developed with funding from the eXtension Foundation
# === LICENSE:
#
# see LICENSE file


class ImagesController < ApplicationController

  def index
    @pagination_params = {}
    @filter_strings = []
    @filtered = false

    if(params[:community_id] and @community = Group.find_by_id(params[:community_id]))
      @pagination_params[:community_id] = params[:community_id]
      @filter_strings << "Community: #{@community.name}"
      @filtered = true
      image_scope = @community.hosted_images
    else
      image_scope = HostedImage.linked
    end


    if(@page_status = params[:page_status])
      @filtered = true
      @filter_strings << "Page Status: #{@page_status}"
      case @page_status
      when 'All'
        @filtered = false
        image_scope = (@community.nil? ? HostedImage.linked : @community.hosted_images)
      when 'Viewed'
        image_scope = (@community.nil? ? HostedImage.viewed(true) : @community.hosted_images.viewed(true))
      when 'Unviewed'
        image_scope = (@community.nil? ? HostedImage.viewed(false) : @community.hosted_images.viewed(false))
      else
        @filtered = false
        image_scope = (@community.nil? ? HostedImage.linked : @community.hosted_images)
      end
    end


    if(@stock = params[:stock])
      if(TRUE_VALUES.include?(params[:stock]))
        @stock = 'Yes'
      elsif(FALSE_VALUES.include?(params[:stock]))
        @stock = 'No'
      end
      @pagination_params[:stock] = @stock
      @filter_strings << "Stock status: #{@stock}"
      @filtered = true
      image_scope = image_scope.stock(@stock)
    end

    if(@community_reviewed = params[:community_reviewed])
      @pagination_params[:community_reviewed] = @community_reviewed
      @filter_strings << "Community copyright review status: #{@community_reviewed}"
      @filtered = true
      image_scope = image_scope.community_reviewed(@community_reviewed)
    end

    if(@staff_reviewed = params[:staff_reviewed])
      @pagination_params[:staff_reviewed] = @staff_reviewed
      @filter_strings << "Staff copyright review status: #{@staff_reviewed}"
      @filtered = true
      image_scope = image_scope.staff_reviewed(@staff_reviewed)
    end

    if(!params[:copyrightsearch].blank?)
      @pagination_params[:copyrightsearch] = params[:copyrightsearch]
      @filter_strings << "Copyright text has following terms: #{params[:copyrightsearch]}"
      @filtered = true
      image_scope = image_scope.search_copyright_terms(params[:copyrightsearch])
    end

    if(@community.nil? and !@filtered)
      image_scope = image_scope.linked
    end

    @images = image_scope.order("hosted_images.id desc").page(params[:page]).per(10)
  end

  def show
    @image = HostedImage.find(params[:id])
  end

  def change_communityreview
    @image = HostedImage.find(params[:id])
    if(!params[:community_reviewed].nil?)
      previous_value = @image.community_reviewed
      if(params[:community_reviewed] == 'clear')
        @image.update_attributes({community_reviewed: nil, community_reviewed_by: nil})
        AuditLog.create(contributor: @currentcontributor,
                        auditable: @image,
                        changed_item: 'community_reviewed',
                        previous_check_value: previous_value,
                        current_check_value: nil)
      else
        community_reviewed = TRUE_VALUES.include?(params[:community_reviewed])
        @image.update_attributes({community_reviewed: community_reviewed, community_reviewed_by: @currentcontributor.id})
        AuditLog.create(contributor: @currentcontributor,
                        auditable: @image,
                        changed_item: 'community_reviewed',
                        previous_check_value: previous_value,
                        current_check_value: @image.community_reviewed?)
      end
    end
  end

  def change_staffreview
    @image = HostedImage.find(params[:id])
    if(!params[:staff_reviewed].nil?)
      previous_value = @image.staff_reviewed
      if(params[:staff_reviewed] == 'clear')
        @image.update_attributes({staff_reviewed: nil, staff_reviewed_by: nil})
        AuditLog.create(contributor: @currentcontributor,
                        auditable: @image,
                        changed_item: 'staff_reviewed',
                        previous_check_value: previous_value,
                        current_check_value: nil)
      else
        staff_reviewed = TRUE_VALUES.include?(params[:staff_reviewed])
        @image.update_attributes({staff_reviewed: staff_reviewed, staff_reviewed_by: @currentcontributor.id})
        AuditLog.create(contributor: @currentcontributor,
                        auditable: @image,
                        changed_item: 'staff_reviewed',
                        previous_check_value: previous_value,
                        current_check_value: @image.staff_reviewed?)
      end
    end
  end


  def change_stock
    @image = HostedImage.find(params[:id])
    if(!params[:is_stock].nil?)
      previous_value = @image.is_stock
      if(params[:is_stock] == 'clear')
        @image.update_attributes({is_stock: nil, is_stock_by: nil})
        AuditLog.create(contributor: @currentcontributor,
                        auditable: @image,
                        changed_item: 'is_stock',
                        previous_check_value: previous_value,
                        current_check_value: nil)
      else
        is_stock = TRUE_VALUES.include?(params[:is_stock])
        @image.update_attributes({is_stock: is_stock, is_stock_by: @currentcontributor.id})
        AuditLog.create(contributor: @currentcontributor,
                        auditable: @image,
                        changed_item: 'is_stock',
                        previous_check_value: previous_value,
                        current_check_value: @image.is_stock)
      end

    end
  end

  def set_notes
    @image = HostedImage.find(params[:id])

    if(params[:commit] == 'Save Changes')
      previous_notes = @image.notes
      @image.update_attribute(:notes,params[:hosted_image][:notes])
      AuditLog.create(contributor: @currentcontributor,
                      auditable: @image,
                      changed_item: 'notes',
                      previous_notes: previous_notes,
                      current_notes: @image.notes)
    end
    respond_to do |format|
      format.js
    end
  end

  def bulk_change_stock_and_staff_review
    selected_images = params[:selected_image_ids]

    if !selected_images.nil?
      selected_images.each do |image_id|
        HostedImage.bulk_change_stock_and_staff_review(image_id, @currentcontributor.id)
      end
    end

    redirect_to images_path(staff_reviewed: "Unreviewed")
  end

end

app/views/images/_community_review.html.erb
<div class="dashmodule">
  <%- if @image.community_reviewed.nil? -%>
    <p><strong>Community Review:</strong> <span class="label label-info">Not Yet Reviewed</span></p>
    <p>
      <%= link_to('Copyright complete',change_communityreview_image_path({id: @image.id, community_reviewed: 'yes'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
      <%= link_to('Copyright incomplete',change_communityreview_image_path({id: @image.id, community_reviewed: 'no'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>

    </p>
  <%- elsif @image.community_reviewed? -%>
    <p><strong>Community Review:</strong> <span class="label label-success">Copyright complete</span></p>
    <p><small>Community copyright review from <%= @image.community_reviewer.fullname -%></small></p>
    <p>
      <%= link_to('Copyright incomplete',change_communityreview_image_path({id: @image.id, community_reviewed: 'no'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>
      <%= link_to('Clear review',change_communityreview_image_path({id: @image.id, community_reviewed: 'clear'}), :class => "btn btn-link btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- else -%>
    <p><strong>Community Review:</strong> <span class="label label-warning">Copyright incomplete</span></p>
    <p><small>Community copyright review from <%= @image.community_reviewer.fullname -%></small></p>
    <p>
    <%= link_to('Copyright complete',change_communityreview_image_path({id: @image.id, community_reviewed: 'yes'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
    <%= link_to('Clear review',change_communityreview_image_path({id: @image.id, community_reviewed: 'clear'}), :class => "btn btn-link btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- end -%>
</div>

app/views/images/_filter_form.html.erb
<div class="row">
  <div class="col-md-12">
  <div class="well">
    <%= form_tag(images_path, class: 'form-horizontal', :method => :get) do -%>
      <%- if @community -%>
        <%= hidden_field_tag(:community_id, @community.id) -%>
      <%- end -%>

      <div class="form-group">
        <div class="col-md-offset-1 col-md-8">
          <legend>Filter list by:</legend>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag('page_status', 'Containing Page(s) Status', :class => 'col-md-3 control-label') -%>
        <div class="col-md-2">
          <%= select_tag("page_status",options_for_select([ "All","Viewed","Unviewed"], @page_status || "All"), class: 'form-control' ) -%>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag('stock', 'Stock Photo Status', :class => 'col-md-3 control-label') -%>
        <div class="col-md-2">
          <%= select_tag("stock",options_for_select([ "All", "Reviewed","Unreviewed","Yes","No"], @stock || "All"), class: 'form-control' ) -%>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag('community_reviewed', 'Copyright reviewed by community', :class => 'col-md-3 control-label') -%>
        <div class="col-md-2">
          <%= select_tag("community_reviewed",options_for_select([ "All", "Reviewed","Unreviewed","Complete","Incomplete"], @community_reviewed || "All"), class: 'form-control' ) -%>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag('staff_reviewed', 'Copyright reviewed by staff', :class => 'col-md-3 control-label') -%>
        <div class="col-md-2">
          <%= select_tag("staff_reviewed",options_for_select([ "All", "Reviewed","Unreviewed","Complete","Incomplete"], @staff_reviewed || "All"), class: 'form-control' ) -%>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag('copyrightsearch', 'Copyright search terms', :class => 'col-md-3 control-label') -%>
        <div class="col-md-5">
          <%= text_field_tag("copyrightsearch", params[:copyrightsearch], placeholder: 'Separate terms by commas (e.g. creative commons, cc, creativecommons)', class: 'form-control' ) -%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-3 col-md-8">
          <p>
            <%= submit_tag "Apply Filter", :name => nil, :class => "btn btn-default btn-primary" %>
            <%= link_to "cancel", '#', :class => "btn btn-default", :id => 'cancel_button' %>
          </p>
        </div>
      </div>

    <%- end # end form -%>
  </div>
  </div>
</div>

<script class="code" type="text/javascript">

    $('#cancel_button').on('click', function () {
      $('#showform').collapse('hide');
    });

 </script>

app/views/images/_image_audit_notes.html.erb
<div class='image_audit_notes'>
<%- if(@image.notes.present?) -%>
  <%= @image.notes.html_safe %>
<%- else -%>
    <p><em>No notes provided</em></p>
<%- end -%>

<%- if @currentcontributor -%>
  <p id="edit_notes_link_for_image_<%= @image.id %>"><small><%= link_to('edit','#',id: "edit_notes_for_image_#{@image.id}") %></small></p>
<%- end -%>

<script class="code" type="text/javascript">
  $('#edit_notes_for_image_<%= @image.id %>').click(function() {
    $('#edit_notes_link_for_image_<%= @image.id %>').hide();
    $('#notes_for_image_<%= @image.id %>').html('<%= escape_javascript(render(partial: "image_audit_notes_form", locals: {image: @image})) %>');
 });
</script>
</div>

app/views/images/_image_audit_notes_form.html.erb
<%= form_for(image, :url => set_notes_image_path(id: image.id), remote: true, html: {id: "notes_form_for_image_#{image.id}"}) do |f| %>

  <div class="form-group">
    <fieldset>
      <%= f.text_area :notes, "rows" => 5, class: 'col-md-8', id: "image_notes_field_#{image.id}" %>
    </fieldset>
  </div>

  <p>
    <%= f.submit "Save Changes", :class => "btn btn-primary" -%>
    <%= f.submit('cancel', :class => 'btn btn-link') -%>
  </p>

<%- end -%>

<script class="code" type="text/javascript">
  $('#image_notes_field_<%= image.id %>').wysihtml5({toolbar: { "fa": true, "link": false, "image": false}});
</script>

app/views/images/_staff_review.html.erb
<div class="dashmodule">
  <%- if @image.staff_reviewed.nil? -%>
    <p><strong>Staff Review:</strong> <span class="label label-info">Not Yet Reviewed</span></p>
    <p>
      <%= link_to('Copyright complete',change_staffreview_image_path({id: @image.id, staff_reviewed: 'yes'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
      <%= link_to('Copyright incomplete',change_staffreview_image_path({id: @image.id, staff_reviewed: 'no'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>

    </p>
  <%- elsif @image.staff_reviewed? -%>
    <p><strong>Staff Review:</strong> <span class="label label-success">Copyright complete</span></p>
    <p><small>Staff copyright review from <%= @image.staff_reviewer.fullname -%></small></p>
    <p>
      <%= link_to('Copyright incomplete',change_staffreview_image_path({id: @image.id, staff_reviewed: 'no'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>
      <%= link_to('Clear review',change_staffreview_image_path({id: @image.id, staff_reviewed: 'clear'}), :class => "btn btn-link btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- else -%>
    <p><strong>Staff Review:</strong> <span class="label label-warning">Copyright incomplete</span></p>
    <p><small>Staff copyright review from <%= @image.staff_reviewer.fullname -%></small></p>
    <p>
    <%= link_to('Copyright complete',change_staffreview_image_path({id: @image.id, staff_reviewed: 'yes'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
    <%= link_to('Clear review',change_staffreview_image_path({id: @image.id, staff_reviewed: 'clear'}), :class => "btn btn-link btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- end -%>
</div>

app/views/images/_stock_button.html.erb
<div class="dashmodule">
  <%- if @image.is_stock.nil? -%>
    <p><strong>Stock Image:</strong> <span class="label label-info">Not Yet Reviewed</span></p>
    <p>
      <%= link_to('Stock Image',change_stock_image_path({id: @image.id, is_stock: 'yes'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>
      <%= link_to('Not a Stock Image',change_stock_image_path({id: @image.id, is_stock: 'no'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- elsif @image.is_stock? -%>
    <p><strong>Stock Image:</strong> <span class="label label-warning">YES</span></p>
    <p><small>Stock image review from <%= @image.is_stock_reviewer.fullname -%></small></p>
    <p>
    <%= link_to('Not a Stock Image',change_stock_image_path({id: @image.id, is_stock: 'no'}), :class => "btn btn-success btn-sm", :remote => true, :method => :post) -%>
    <%= link_to('Clear review',change_stock_image_path({id: @image.id, is_stock: 'clear'}), :class => "btn btn-link btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- else -%>
    <p><strong>Stock Image:</strong> <span class="label label-success">NO</span></p>
    <p><small>Stock image review from <%= @image.is_stock_reviewer.fullname -%></small></p>
    <p>
    <%= link_to('Stock Image',change_stock_image_path({id: @image.id, is_stock: 'yes'}), :class => "btn btn-warning btn-sm", :remote => true, :method => :post) -%>
    <%= link_to('Clear review',change_stock_image_path({id: @image.id, is_stock: 'clear'}), :class => "btn btn-link btn-sm", :remote => true, :method => :post) -%>
    </p>
  <%- end -%>
</div>

app/views/images/change_communityreview.js.erb
$("#communityreview").html("<%= escape_javascript(render(:partial => 'community_review')) %>")

app/views/images/change_staffreview.js.erb
$("#staffreview").html("<%= escape_javascript(render(:partial => 'staff_review')) %>")

app/views/images/change_stock.js.erb
$("#stockbutton").html("<%= escape_javascript(render(:partial => 'stock_button')) %>")

app/views/images/index.html.erb
<div class="page-header">
<h1>Images</h1>
<%- if !@filter_strings.blank? -%>
<p>Filtered by: <%= @filter_strings.join(' | ') -%></p>
<%- end -%>
<p>
  <%= link_to("<i class='fa fa-search'></i> Filter this list".html_safe,
              '#',
              id: 'formtoggler',
              class: 'btn btn-default',
              data: {toggle: 'collapse', target: '#showform'}) %>
</p>
<div id="showform" class="<%= (@showform ? 'collapse in' : 'collapse') -%>">
  <%= render(:partial => 'images/filter_form') %>
</div>
</div>

<div id="paginator_wrapper">
  <%- if @images.length > 0 -%>
    <p class="display_results">Displaying <strong><%= @images.offset_value + 1 %>-<%= @images.offset_value + @images.length %></strong> of <strong><%= @images.total_count %></strong></p>
  <%- else -%>
      <p class="display_results">Displaying <strong>0</strong> of <strong>0</strong></p>
  <%- end -%>
  <%= paginate @images, :params => @pagination_params %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID#</th>
      <th>Image</th>
      <th>Pages</th>
      <th>Source</th>
      <th>Stock?</th>
      <th>Copyright</th>
      <th>Copyright Reviewed?</th
    </tr>
  </thead>
  <tbody>
    <%= form_tag bulk_change_stock_and_staff_review_path(method: :post) do %>  
      <%- @images.each do |image| -%>
        <tr>
          <td><%= image.id -%> (<%= link_to('details',image_path(image.id)) -%>)
              <% if request.fullpath == "/images?staff_reviewed=Unreviewed" -%>
                <%= check_box_tag 'selected_image_ids[]', image.id -%>
              <%- end -%>
          </td>
          <td><%= imageaudit_link(image) -%></td>
          <td>
              <%- image.page_ids.each do |pid | -%>
                <%= link_to("#{pid}",page_path(pid)) -%>,
              <%- end -%>
          </td>
          <td><%= imageaudit_sourcelink(image) -%>
            <%- if(image.source == 'create' and image.original_wiki?) -%>
              <br/><em> originally copwiki </em>
            <%- end -%>
          </td>
          <td>
            <%- if image.is_stock.nil? -%>
              <span class="label label-info">not reviewed</span>
            <%- elsif image.is_stock? -%>
              <span class="label label-warning">Yes</span>
            <%- else -%>
              <span class="label label-success">No</span>
            <%- end -%>
          </td>
          <td><%= image.copyright -%></td>
          <td>
              Community:
              <%- if image.community_reviewed.nil? -%>
                <span class="label label-info">not reviewed</span>
              <%- elsif image.community_reviewed? -%>
                <span class="label label-success">Complete</span>
              <%- else -%>
                <span class="label label-warning">Incomplete</span>
              <%- end -%>
              <br/>
              Staff:
              <%- if image.staff_reviewed.nil? -%>
                <span class="label label-info">not reviewed</span>
              <%- elsif image.staff_reviewed? -%>
                <span class="label label-success">Complete</span>
              <%- else -%>
                <span class="label label-warning">Incomplete</span>
              <%- end -%>
          </td>
        </tr>
      <%- end -%>
      <% if request.fullpath == "/images?staff_reviewed=Unreviewed" -%>
        <%= submit_tag "Update Selected Images" -%>
        <p>Use this button to update the staff reviewed status to 'yes' and the is stock status to 'no' on the images checked below</p>
        <input type="checkbox" id="selectAll" value="selectAll"> Select / Deselect All<br/><br/>
      <%- end -%>
    <%- end -%>
    </tbody>
  </table>

  <script type="text/javascript">

  $('#showform').on('show', function () {
    $('#formtoggler').html("Filter Options <i class='fa fa-caret-down'></i>");
  });

  $('#showform').on('hide', function () {
    $('#formtoggler').html("Filter Options <i class='fa fa-caret-right'></i>");
  });
  $('#selectAll').click(function() {
   if (this.checked) {
       $(':checkbox').each(function() {
           this.checked = true;                        
       });
   } else {
      $(':checkbox').each(function() {
           this.checked = false;                        
       });
   } 
});
  </script>

app/views/images/set_notes.js.erb
$("#notes_for_image_<%= @image.id %>").html("<%= escape_javascript(render partial: 'image_audit_notes', locals: {image: @image}) %>");
$('#edit_notes_link_for_image_<%= @image.id %>').show();

app/views/images/show.html.erb
<h1>Image Details for Hosted Image ID# <%= @image.id -%></h1>
<div class="row">
  <div class="col-md-6">
    <table class="table">
        <tr>
      		<td>Image</td>
        	<td><%= imageaudit_link(@image) -%></td>
        </tr>
        <tr>
            <td>Source</td>
            <td>
              <%= imageaudit_sourcelink(@image) -%>
              <%- if(@image.source == 'create' and @image.original_wiki?) -%>
                <br/><em> metadata imported from copwiki image information </em>
              <%- end -%>
            </td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @image.description.nil? ? '<em>none</em>'.html_safe : @image.description %></td>
        </tr>
        <tr>
            <td>Copyright</td>
            <td><%= @image.copyright.nil? ? '<em>none</em>'.html_safe : @image.copyright %></td>
        </tr>
    </table>
  </div>
  <div class="col-md-6 text-center">
    <div id="stockbutton">
      <%= render(partial: 'stock_button') -%>
    </div>
    <div id="communityreview">
      <%= render(partial: 'community_review') -%>
    </div>
    <div id="staffreview">
      <%= render(partial: 'staff_review') -%>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading"
      <h3 class="panel-title">Image Notes</h3>
      </div>
      <div class="panel-body">
        <div id='notes_for_image_<%= @image.id %>'>
          <%= render(partial: 'image_audit_notes', locals: {image: @image}) %>
        </div>

      </div>
    </div>
  </div>
</div>




<%- if @image.pages.count > 0 -%>
<h2>Pages</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Page ID#</th>
      <th>Page Title</th>
      <th>Total Unique Pageviews</th>
      <th>Mean Unique Pageviews</th>
      <th>Source Page Created At</th>
      <th>Source Page Last Updated At</th>
    </tr>
  </thead>
  <tbody>
    <%- @image.pages.each do |page| -%>
      <tr>
        <td><%= page.id -%> (<%= link_to('details',page_path(page.id)) -%>)</td>
        <td><%= page.title -%> (<%= pageinfo_link(page.id,'page info') -%>)</td>
        <td><%= number_with_delimiter(page.unique_pageviews) -%></td>
        <td><%= number_with_precision(page.mean_unique_pageviews, precision: 2) -%></td>
        <td><%= page.source_created_at.to_s -%></td>
        <td><%= page.source_updated_at.to_s -%></td>
      </tr>
    <%- end -%>
    </tbody>
  </table>
<%- end -%>